name: Docker Deployment

# This defines the event that triggers the workflow
on:
  push:
    branches:
      - main  # Trigger on push to the main branch

# Job to build and deploy the Docker container
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # This defines the OS used to run the job

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:v2:${{ github.sha }} .

      # Step 5: Push the image to Docker Hub (or other Docker registry)
      - name: Push Docker image
        run: |
          docker push my-app:v2:${{ github.sha }}

      # Step 6: Deploy the Docker container to the server (e.g., via SSH)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          script: |
            docker pull my-app:v2:${{ github.sha }}
            docker stop my-app:v2 || true
            docker rm my-appv2 || true
            docker run -d --name my-appv2 -p 8084:80 my-app:${{ github.sha }}
